### ISSUE TITLE
PIA生成蜂窝曲面

### ISSUE THREAD

**Issue by lavender-lee** [wangbolun300/Scattered_Points_Interpolation#2]
Dr Wang
你好，请教一下，使用PIA我发现很容易产生蜂窝状的曲面，我测试了很多模型都是类似这样

![image](https://user-images.githubusercontent.com/35004095/219954044-3904f03a-4ef2-4bb8-981f-64da632f3eba.png)

![image](https://user-images.githubusercontent.com/35004095/219954057-7efa2cce-8360-42d2-80d5-f3e736989799.png)

![image](https://user-images.githubusercontent.com/35004095/219954078-9b471140-37ba-437c-ab6f-5578e9081601.png)

**Comment by wangbolun300** [comment]
你好，
产生这个现象的原因是因为曲面求解过程中的fairness不够大导致的。因为我提供的代码已经将参数固定，可能并不是在所有数据密度情况下都十分合理。出现这个问题的原因，大概率是在迭代过程中，逼近数据点的能量的参数选择过大，使得每次迭代中没有数据点对应的曲面片的运动滞后，从而导致曲面不光滑。你可以尝试一下将曲面的拉普拉斯能量的参数调大，来看看会不会有质量的提升。
如果你感兴趣的话，可以以这份代码为底层算法，再设计一个交互式的参数输入界面，动态地根据得到的运行结果调整参数，来避免这个问题 （这也是我一直想做的，但是一直因为没有时间导致没有完成这个功能）。

**Comment by lavender-lee** [comment]
好的，谢谢老师指导哈。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Bolun Wang ***@***.***>
发送时间: Sunday, February 19, 2023 10:41:11 PM
收件人: wangbolun300/Scattered_Points_Interpolation ***@***.***>
抄送: Shutao Tang ***@***.***>; Author ***@***.***>
主题: Re: [wangbolun300/Scattered_Points_Interpolation] PIA生成蜂窝曲面 (Issue #2)


你好，
产生这个现象的原因是因为曲面求解过程中的fairness不够大导致的。因为我提供的代码已经将参数固定，可能并不是在所有数据密度情况下都十分合理。出现这个问题的原因，大概率是在迭代过程中，逼近数据点的能量的参数选择过大，使得每次迭代中没有数据点对应的曲面片的运动滞后，从而导致曲面不光滑。你可以尝试一下将曲面的拉普拉斯能量的参数调大，来看看会不会有质量的提升。
如果你感兴趣的话，可以以这份代码为底层算法，再设计一个交互式的参数输入界面，动态地根据得到的运行结果调整参数，来避免这个问题。

―

**Comment by wangbolun300** [comment]
我刚刚收到你的来信，首先感谢您对这篇文章的关注。为了方便，我在这里对你提到的一些问题做一下回答：

（1）网格边缘数据稀疏，导致重构效果差的问题，根据你发来的图片，我认为和“蜂窝状”网格产生的原因是一致的，都是因为参数设置不合理导致的。你发来的图片中，网格边缘产生了折叠，这明显是因为网格并没有在收敛过程中保持一直光滑。
设置曲面控制点个数的方法是我的一个经验值，你可以根据需要自己设置值。网格的顶点的疏密在不同区域有较大差别的话，可能这种用经验值来设置的方法就不是很合理。你说的误差降不下去的问题，我猜想有两个主要原因。第一个，是局部有些点的密度过大，导致局部控制点的数量不够产生一个光滑又精确的解。第二个，精度和光滑度可以认为是有一定矛盾的，不合理的参数设置可能导致精度的下降，或者不光滑情况的产生。

（2）本文算法局部能量高的原因有可能是参数设置不合理。你可以试试增加per。per越大，控制点越多，得到的曲面越光滑。或者，用文章中提出的节点插入的方法，也会让曲面在每次迭代中越来越光滑。但是由于代码中对Eigen库的不合理使用，节点插入可能会比较消耗计算资源。有兴趣的话可以对Eigen的系数矩阵求解部分进行修改，我可能最近没有时间对这些代码中的遗留问题进行修改。
（3）论文中的mask的参数应该是写在了论文里，如果论文里没有提及，那么就应该是用的默认参数。
（4）我不确定mask模型是哪个软件生成的。我也是从别人那里获取的模型。
