### ISSUE TITLE
Multiple definition when Linking CXX executable Sparse_Interp_bin

### ISSUE THREAD

**Issue by dikennek** [wangbolun300/Scattered_Points_Interpolation#3]
![erreur multiple definition](https://github.com/wangbolun300/Scattered_Points_Interpolation/assets/74213844/50cc21a8-814d-4f63-a71b-a6a617c4d044)

Hello,
I have an error in the compilation process, i hope i have followed the read me as it should be.
The error is a multiple definition (as show in the attachement), but i didn't know where it came and how to fix it.
I am using WSL with Ubuntu and Cmake version 3.22.1.
i am looking forward to reading from you.
Kind regards,
Théo

**Comment by wangbolun300** [comment]
can you delete everything in the build folder and do cmake/make again? I don't have a ubuntu but I just tried it on my MacBook and it works well.

**Comment by dikennek** [comment]
Unfortunately, it didn't fix the problem.

**Comment by wangbolun300** [comment]
I am using cmake version 3.26.4, maybe update your camke version?
